export const locationList = [
  {
    city: "Sylhet",
    upazilas: [
      "Sylhet Sadar",
      "South Surma",
      "Osmani Nagar",
      "Beanibazar",
      "Golapganj",
      "Bishwanath",
      "Balaganj",
      "Kanaighat",
      "Zakiganj",
      "Jaintiapur",
      "Companiganj",
      "Gowainghat",
      "Fenchuganj",
    ],
  },
  {
    city: "Dhaka",
    upazilas: [
      "Dhamrai",
      "Dohar",
      "Keraniganj",
      "Nawabganj",
      "Savar",
      "Adabor",
      "Badda",
      "Bangshal",
      "Bimanbandar",
      "Cantonment",
      "Chawkbazar",
      "Dakshinkhan",
      "Demra",
      "Dhanmondi",
      "Gendaria",
      "Gulshan",
      "Hazaribagh",
      "Jatrabari",
      "Kadamtali",
      "Kalabagan",
      "Kamrangirchar",
      "Khilkhet",
      "Khilgaon",
      "Kotwali",
      "Lalbagh",
      "Mirpur",
      "Mohammadpur",
      "Motijheel",
      "Paltan",
      "Ramna",
      "Rampura",
      "Sabujbagh",
      "Shah Ali",
      "Shahbagh",
      "Sher-e-Bangla Nagar",
      "Sutrapur",
      "Tejgaon",
      "Tejgaon Industrial Area",
      "Turag",
      "Uttara Khan",
      "Uttara",
      "Vatara",
    ],
  },
  {
    city: "Chittagong",
    upazilas: [
      "Anwara",
      "Banshkhali",
      "Boalkhali",
      "Chandanaish",
      "Fatikchhari",
      "Hathazari",
      "Karnaphuli",
      "Lohagara",
      "Mirsharai",
      "Patiya",
      "Rangunia",
      "Raozan",
      "Sandwip",
      "Satkania",
      "Sitakunda",
      "Bakalia",
      "Bayazid Bostami",
      "Chandgaon",
      "Double Mooring",
      "Halishahar",
      "Khulshi",
      "Kotwali",
      "Pahartali",
      "Panchlaish",
      "Patenga",
    ],
  },
  {
    city: "Rajshahi",
    upazilas: [
      "Bagha",
      "Bagmara",
      "Charghat",
      "Durgapur",
      "Godagari",
      "Mohanpur",
      "Paba",
      "Puthiya",
      "Tanore",
      " বোয়ালিয়া",
      "মতিহার",
      "শাহ মখদুম",
      "কর্ণহার",
    ],
  },
  {
    city: "Khulna",
    upazilas: [
      "Batiaghata",
      "Dacope",
      "Dumuria",
      "Dighalia",
      "Kachua",
      "Paikgachha",
      "Phultala",
      "Rupsa",
      "Terokhada",
      "Atrai",
      "Baraigram",
      "Bagatipara",
      "Gurudaspur",
      "Lalpur",
      "Naldanga",
      "Singra",
      "Khulna Sadar",
      "Sonadanga",
      "Khalishpur",
      "Daulatpur",
      "Khan Jahan Ali",
    ],
  },
  {
    city: "Barishal",
    upazilas: [
      "Muladi",
      "Babuganj",
      "Wazirpur",
      "Banaripara",
      "Gaurnadi",
      "Agailjhara",
      "Barishal Sadar",
      "Bakerganj",
      "Mehendiganj",
      "Hizla",
    ],
  },
  {
    city: "Mymensingh",
    upazilas: [
      "Bhaluka",
      "Trishal",
      "Gaffargaon",
      "Nandail",
      "Ishwarganj",
      "Phulpur",
      "Haluaghat",
      "Dhobaura",
      "Fulbaria",
      "Gauripur",
      "Muktagachha",
      "Tara Khanda",
      "Mymensingh Sadar",
    ],
  },
  {
    city: "Rangpur",
    upazilas: [
      " বদরগঞ্জ",
      "গংগাচড়া",
      "কাউনিয়া",
      "পীরগাছা",
      "পীরগঞ্জ",
      "তারাগঞ্জ",
      "রংপুর সদর",
      "মিঠাপুকুর",
    ],
  },
];
