export const BLOOD_GROUPS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const DEFAULT_LOCATION = {
  address: "Unknown",
  upazila: "",
  city: "Dhaka",
};

export const ITEM_PER_PAGE = 9;

export const BLOOD_TYPES = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
] as const;

// export const STATES = [
//   "Abia",
//   "Adamawa",
//   "Akwa Ibom",
//   "Anambra",
//   "Bauchi",
//   "Bayelsa",
//   "Benue",
//   "Borno",
//   "Cross River",
//   "Delta",
//   "Ebonyi",
//   "Edo",
//   "Ekiti",
//   "Enugu",
//   "FCT",
//   "Gombe",
//   "Imo",
//   "Jigawa",
//   "Kaduna",
//   "Kano",
//   "Katsina",
//   "Kebbi",
//   "Kogi",
//   "Kwara",
//   "Lagos",
//   "Nasarawa",
//   "Niger",
//   "Ogun",
//   "Ondo",
//   "Osun",
//   "Oyo",
//   "Plateau",
//   "Rivers",
//   "Sokoto",
//   "Taraba",
//   "Yobe",
//   "Zamfara",
// ] as const;
export const locationList = [
  {
    city: "BARGUNA",
    upazilas: [
      "AMTALI",
      "BAMNA",
      "BARGUNA SADAR",
      "BETAGI",
      "PATHARGHATA",
      "TALTALI",
    ],
  },
  {
    city: "BARISAL",
    upazilas: [
      "AGAILJHARA",
      "BABUGANJ",
      "BAKERGANJ",
      "BANARI PARA",
      "GAURNADI",
      "HIZLA",
      "BARISAL SADAR (KOTWALI)",
      "MHENDIGANJ",
      "MULADI",
      "WAZIRPUR",
    ],
  },
  {
    city: "BHOLA",
    upazilas: [
      "BHOLA SADAR",
      "BURHANUDDIN",
      "CHAR FASSON",
      "DAULAT KHAN",
      "LALMOHAN",
      "MANPURA",
      "TAZUMUDDIN",
    ],
  },
  {
    city: "JHALOKATI",
    upazilas: ["JHALOKATI SADAR", "KANTHALIA", "NALCHITY", "RAJAPUR"],
  },
  {
    city: "PATUAKHALI",
    upazilas: [
      "BAUPHAL",
      "DASHMINA",
      "DUMKI",
      "GALACHIPA",
      "KALAPARA",
      "MIRZAGANJ",
      "PATUAKHALI SADAR",
      "RANGABALI",
    ],
  },
  {
    city: "PIROJPUR",
    upazilas: [
      "BHANDARIA",
      "KAWKHALI",
      "MATHBARIA",
      "NAZIRPUR",
      "PIROJPUR SADAR",
      "NESARABAD (SWARUPKATI)",
      "ZIANAGAR",
    ],
  },
  {
    city: "BANDARBAN",
    upazilas: [
      "ALIKADAM",
      "BANDARBAN SADAR",
      "LAMA",
      "NAIKHONGCHHARI",
      "ROWANGCHHARI",
      "RUMA",
      "THANCHI",
    ],
  },
  {
    city: "BRAHMANBARIA",
    upazilas: [
      "AKHAURA",
      "BANCHHARAMPUR",
      "BIJOYNAGAR",
      "BRAHMANBARIA SADAR",
      "ASHUGANJ",
      "KASBA",
      "NABINAGAR",
      "NASIRNAGAR",
      "SARAIL",
    ],
  },
  {
    city: "CHANDPUR",
    upazilas: [
      "CHANDPUR SADAR",
      "FARIDGANJ",
      "HAIM CHAR",
      "HAJIGANJ",
      "KACHUA",
      "MATLAB DAKSHIN",
      "MATLAB UTTAR",
      "SHAHRASTI",
    ],
  },
  {
    city: "CHITTAGONG",
    upazilas: [
      "ANOWARA",
      "BAYEJID BOSTAMI",
      "BANSHKHALI",
      "BAKALIA",
      "BOALKHALI",
      "CHANDANAISH",
      "CHANDGAON",
      "CHITTAGONG PORT",
      "DOUBLE MOORING",
      "FATIKCHHARI",
      "HALISHAHAR",
      "HATHAZARI",
      "KOTWALI",
      "KHULSHI",
      "LOHAGARA",
      "MIRSHARAI",
      "PAHARTALI",
      "PANCHLAISH",
      "PATIYA",
      "PATENGA",
      "RANGUNIA",
      "RAOZAN",
      "SANDWIP",
      "SATKANIA",
      "SITAKUNDA",
    ],
  },
  {
    city: "COMILLA",
    upazilas: [
      "BARURA",
      "BRAHMAN PARA",
      "BURICHANG",
      "CHANDINA",
      "CHAUDDAGRAM",
      "COMILLA SADAR DAKSHIN",
      "DAUDKANDI",
      "DEBIDWAR",
      "HOMNA",
      "COMILLA ADARSHA SADAR",
      "LAKSAM",
      "MANOHARGANJ",
      "MEGHNA",
      "MURADNAGAR",
      "NANGALKOT",
      "TITAS",
    ],
  },
  {
    city: "COX'S BAZAR",
    upazilas: [
      "CHAKARIA",
      "COX'S BAZAR SADAR",
      "KUTUBDIA",
      "MAHESHKHALI",
      "PEKUA",
      "RAMU",
      "TEKNAF",
      "UKHIA",
    ],
  },
  {
    city: "FENI",
    upazilas: [
      "CHHAGALNAIYA",
      "DAGANBHUIYAN",
      "FENI SADAR",
      "FULGAZI",
      "PARSHURAM",
      "SONAGAZI",
    ],
  },
  {
    city: "KHAGRACHHARI",
    upazilas: [
      "DIGHINALA",
      "KHAGRACHHARI SADAR",
      "LAKSHMICHHARI",
      "MAHALCHHARI",
      "MANIKCHHARI",
      "MATIRANGA",
      "PANCHHARI",
      "RAMGARH",
    ],
  },
  {
    city: "LAKSHMIPUR",
    upazilas: [
      "KAMALNAGAR",
      "LAKSHMIPUR SADAR",
      "ROYPUR",
      "RAMGANJ",
      "RAMGATI",
    ],
  },
  {
    city: "NOAKHALI",
    upazilas: [
      "BEGUMGANJ",
      "CHATKHIL",
      "COMPANIGANJ",
      "HATIYA",
      "KABIRHAT",
      "SENBAGH",
      "SONAIMURI",
      "SUBARNACHAR",
      "NOAKHALI SADAR",
    ],
  },
  {
    city: "RANGAMATI",
    upazilas: [
      "BAGHAICHHARI",
      "BARKAL UPAZILA",
      "KAWKHALI (BETBUNIA)",
      "BELAI CHHARI UPAZI",
      "KAPTAI UPAZILA",
      "JURAI CHHARI UPAZIL",
      "LANGADU UPAZILA",
      "NANIARCHAR UPAZILA",
      "RAJASTHALI UPAZILA",
      "RANGAMATI SADAR UP",
    ],
  },
  {
    city: "DHAKA",
    upazilas: [
      "ADABOR",
      "BADDA",
      "BANGSHAL",
      "BIMAN BANDAR",
      "BANANI",
      "CANTONMENT",
      "CHAK BAZAR",
      "DAKSHINKHAN",
      "DARUS SALAM",
      "DEMRA",
      "DHAMRAI",
      "DHANMONDI",
      "DOHAR",
      "BHASAN TEK",
      "BHATARA",
      "GENDARIA",
      "GULSHAN",
      "HAZARIBAGH",
      "JATRABARI",
      "KAFRUL",
      "KADAMTALI",
      "KALABAGAN",
      "KAMRANGIR CHAR",
      "KHILGAON",
      "KHILKHET",
      "KERANIGANJ",
      "KOTWALI",
      "LALBAGH",
      "MIRPUR",
      "MOHAMMADPUR",
      "MOTIJHEEL",
      "MUGDA PARA",
      "NAWABGANJ",
      "NEW MARKET",
      "PALLABI",
      "PALTAN",
      "RAMNA",
      "RAMPURA",
      "SABUJBAGH",
      "RUPNAGAR",
      "SAVAR",
      "SHAHJAHANPUR",
      "SHAH ALI",
      "SHAHBAGH",
      "SHYAMPUR",
      "SHER-E-BANGLA NAGAR",
      "SUTRAPUR",
      "TEJGAON",
      "TEJGAON IND. AREA",
      "TURAG",
      "UTTARA PASCHIM",
      "UTTARA PURBA",
      "UTTAR KHAN",
      "WARI",
    ],
  },
  {
    city: "FARIDPUR",
    upazilas: [
      "ALFADANGA",
      "BHANGA",
      "BOALMARI",
      "CHAR BHADRASAN",
      "FARIDPUR SADAR",
      "MADHUKHALI",
      "NAGARKANDA",
      "SADARPUR",
      "SALTHA",
    ],
  },
  {
    city: "GAZIPUR",
    upazilas: ["GAZIPUR SADAR", "KALIAKAIR", "KALIGANJ", "KAPASIA", "SREEPUR"],
  },
  {
    city: "GOPALGANJ",
    upazilas: [
      "GOPALGANJ SADAR",
      "KASHIANI",
      "KOTALIPARA",
      "MUKSUDPUR",
      "TUNGIPARA",
    ],
  },
  {
    city: "JAMALPUR",
    upazilas: [
      "BAKSHIGANJ",
      "DEWANGANJ",
      "ISLAMPUR",
      "JAMALPUR SADAR",
      "MADARGANJ",
      "MELANDAHA",
      "SARISHABARI UPAZILA",
    ],
  },
  {
    city: "KISHOREGONJ",
    upazilas: [
      "AUSTAGRAM",
      "BAJITPUR",
      "BHAIRAB",
      "HOSSAINPUR",
      "ITNA",
      "KARIMGANJ",
      "KATIADI",
      "KISHOREGANJ SADAR",
      "KULIAR CHAR",
      "MITHAMAIN",
      "NIKLI",
      "PAKUNDIA",
      "TARAIL",
    ],
  },
  {
    city: "MADARIPUR",
    upazilas: ["KALKINI", "MADARIPUR SADAR", "RAJOIR", "SHIBCHAR"],
  },
  {
    city: "MANIKGANJ",
    upazilas: [
      "DAULATPUR",
      "GHIOR",
      "HARIRAMPUR",
      "MANIKGANJ SADAR",
      "SATURIA",
      "SHIBALAYA",
      "SINGAIR",
    ],
  },
  {
    city: "MUNSHIGANJ",
    upazilas: [
      "GAZARIA",
      "LOHAJANG",
      "MUNSHIGANJ SADAR",
      "SERAJDIKHAN",
      "SREENAGAR",
      "TONGIBARI",
    ],
  },
  {
    city: "MYMENSINGH",
    upazilas: [
      "BHALUKA",
      "DHOBAURA",
      "FULBARIA",
      "GAFFARGAON",
      "GAURIPUR",
      "HALUAGHAT",
      "ISHWARGANJ",
      "MYMENSINGH SADAR",
      "MUKTAGACHHA",
      "NANDAIL",
      "PHULPUR",
      "TRISHAL",
    ],
  },
  {
    city: "NARAYANGANJ",
    upazilas: [
      "ARAIHAZAR",
      "SONARGAON",
      "BANDAR",
      "NARAYANGANJ SADAR",
      "RUPGANJ",
    ],
  },
  {
    city: "NARSINGDI",
    upazilas: [
      "BELABO",
      "MANOHARDI",
      "NARSINGDI SADAR",
      "PALASH",
      "ROYPURA",
      "SHIBPUR",
    ],
  },
  {
    city: "NETRAKONA",
    upazilas: [
      "ATPARA",
      "BARHATTA",
      "DURGAPUR",
      "KHALIAJURI",
      "KALMAKANDA",
      "KENDUA",
      "MADAN",
      "MOHANGANJ",
      "NETROKONA SADAR",
      "PURBADHALA",
    ],
  },
  {
    city: "RAJBARI",
    upazilas: [
      "BALIAKANDI",
      "GOALANDA",
      "KALUKHALI",
      "PANGSHA",
      "RAJBARI SADAR",
    ],
  },
  {
    city: "SHARIATPUR",
    upazilas: [
      "BHEDARGANJ",
      "DAMUDYA",
      "GOSAIRHAT",
      "NARIA",
      "SHARIATPUR SADAR",
      "ZANJIRA",
    ],
  },
  {
    city: "SHERPUR",
    upazilas: [
      "JHENAIGATI",
      "NAKLA",
      "NALITABARI",
      "SHERPUR SADAR",
      "SREEBARDI",
    ],
  },
  {
    city: "TANGAIL",
    upazilas: [
      "BASAIL",
      "BHUAPUR",
      "DELDUAR",
      "DHANBARI",
      "GHATAIL",
      "GOPALPUR",
      "KALIHATI",
      "MADHUPUR",
      "MIRZAPUR",
      "NAGARPUR",
      "SAKHIPUR",
      "TANGAIL SADAR",
    ],
  },
  {
    city: "BAGERHAT",
    upazilas: [
      "BAGERHAT SADAR",
      "CHITALMARI",
      "FAKIRHAT",
      "KACHUA",
      "MOLLAHAT",
      "MONGLA",
      "MORRELGANJ",
      "RAMPAL",
      "SARANKHOLA",
    ],
  },
  {
    city: "CHUADANGA",
    upazilas: ["ALAMDANGA", "CHUADANGA SADAR", "DAMURHUDA", "JIBAN NAGAR"],
  },
  {
    city: "JESSORE",
    upazilas: [
      "ABHAYNAGAR",
      "BAGHER PARA",
      "CHAUGACHHA",
      "JHIKARGACHHA",
      "KESHABPUR",
      "JESSORE SADAR",
      "MANIRAMPUR",
      "SHARSHA",
    ],
  },
  {
    city: "JHENAIDAH",
    upazilas: [
      "HARINAKUNDA",
      "JHENAIDAH SADAR",
      "KALIGANJ",
      "KOTCHANDPUR",
      "MAHESHPUR",
      "SHAILKUPA",
    ],
  },
  {
    city: "KHULNA",
    upazilas: [
      "BATIAGHATA",
      "DACOPE",
      "DAULATPUR",
      "DUMURIA",
      "DIGHALIA",
      "KHALISHPUR",
      "KHAN JAHAN ALI",
      "KHULNA SADAR",
      "KOYRA",
      "PAIKGACHHA",
      "PHULTALA",
      "RUPSA",
      "SONADANGA",
      "TEROKHADA",
    ],
  },
  {
    city: "KUSHTIA",
    upazilas: [
      "BHERAMARA",
      "DAULATPUR",
      "KHOKSA",
      "KUMARKHALI",
      "KUSHTIA SADAR",
      "MIRPUR",
    ],
  },
  {
    city: "MAGURA",
    upazilas: ["MAGURA SADAR", "MOHAMMADPUR", "SHALIKHA", "SREEPUR"],
  },
  {
    city: "MEHERPUR",
    upazilas: ["GANGNI", "MUJIB NAGAR", "MEHERPUR SADAR"],
  },
  {
    city: "NARAIL",
    upazilas: ["KALIA", "LOHAGARA", "NARAIL SADAR"],
  },
  {
    city: "SATKHIRA",
    upazilas: [
      "ASSASUNI",
      "DEBHATA",
      "KALAROA",
      "KALIGANJ",
      "SATKHIRA SADAR",
      "SHYAMNAGAR",
      "TALA",
    ],
  },
  {
    city: "BOGRA",
    upazilas: [
      "ADAMDIGHI",
      "BOGRA SADAR",
      "DHUNAT",
      "DHUPCHANCHIA",
      "GABTALI",
      "KAHALOO",
      "NANDIGRAM",
      "SARIAKANDI",
      "SHAJAHANPUR",
      "SHERPUR",
      "SHIBGANJ",
      "SONATOLA",
    ],
  },
  {
    city: "JOYPURHAT",
    upazilas: ["AKKELPUR", "JOYPURHAT SADAR", "KALAI", "KHETLAL", "PANCHBIBI"],
  },
  {
    city: "NAOGAON",
    upazilas: [
      "ATRAI",
      "BADALGACHHI",
      "DHAMOIRHAT",
      "MANDA",
      "MAHADEBPUR",
      "NAOGAON SADAR",
      "NIAMATPUR",
      "PATNITALA",
      "PORSHA",
      "RANINAGAR",
      "SAPAHAR",
    ],
  },
  {
    city: "NATORE",
    upazilas: [
      "BAGATIPARA",
      "BARAIGRAM",
      "GURUDASPUR",
      "LALPUR",
      "NATORE SADAR",
      "SINGRA",
    ],
  },
  {
    city: "CHAPAI NABABGANJ",
    upazilas: [
      "BHOLAHAT",
      "GOMASTAPUR",
      "NACHOLE",
      "CHAPAI NABABGANJ SADAR",
      "SHIBGANJ",
    ],
  },
  {
    city: "PABNA",
    upazilas: [
      "ATGHARIA",
      "BERA",
      "BHANGURA",
      "CHATMOHAR",
      "FARIDPUR",
      "ISHWARDI",
      "PABNA SADAR",
      "SANTHIA",
      "SUJANAGAR",
    ],
  },
  {
    city: "RAJSHAHI",
    upazilas: [
      "BAGHA",
      "BAGHMARA",
      "BOALIA",
      "CHARGHAT",
      "DURGAPUR",
      "GODAGARI",
      "MATIHAR",
      "MOHANPUR",
      "PABA",
      "PUTHIA",
      "RAJPARA",
      "SHAH MAKHDUM",
      "TANORE",
    ],
  },
  {
    city: "SIRAJGANJ",
    upazilas: [
      "BELKUCHI",
      "CHAUHALI",
      "KAMARKHANDA",
      "KAZIPUR",
      "ROYGANJ",
      "SHAHJADPUR",
      "SIRAJGANJ SADAR",
      "TARASH",
      "ULLAH PARA",
    ],
  },
  {
    city: "DINAJPUR",
    upazilas: [
      "BIRAMPUR",
      "BIRGANJ",
      "BIRAL",
      "BOCHAGANJ",
      "CHIRIRBANDAR",
      "FULBARI",
      "GHORAGHAT",
      "HAKIMPUR",
      "KAHAROLE",
      "KHANSAMA",
      "DINAJPUR SADAR",
      "NAWABGANJ",
      "PARBATIPUR",
    ],
  },
  {
    city: "GAIBANDHA",
    upazilas: [
      "FULCHHARI",
      "GAIBANDHA SADAR",
      "GOBINDAGANJ",
      "PALASHBARI",
      "SADULLAPUR",
      "SAGHATA",
      "SUNDARGANJ",
    ],
  },
  {
    city: "KURIGRAM",
    upazilas: [
      "BHURUNGAMARI",
      "CHAR RAJIBPUR",
      "CHILMARI",
      "PHULBARI",
      "KURIGRAM SADAR",
      "NAGESHWARI",
      "RAJARHAT",
      "RAUMARI",
      "ULIPUR",
    ],
  },
  {
    city: "LALMONIRHAT",
    upazilas: [
      "ADITMARI",
      "HATIBANDHA",
      "KALIGANJ",
      "LALMONIRHAT SADAR",
      "PATGRAM",
    ],
  },
  {
    city: "NILPHAMARI ZILA",
    upazilas: [
      "DIMLA UPAZILA",
      "DOMAR UPAZILA",
      "JALDHAKA UPAZILA",
      "KISHOREGANJ UPAZILA",
      "NILPHAMARI SADAR UPAZ",
      "SAIDPUR UPAZILA",
    ],
  },
  {
    city: "PANCHAGARH",
    upazilas: ["ATWARI", "BODA", "DEBIGANJ", "PANCHAGARH SADAR", "TENTULIA"],
  },
  {
    city: "RANGPUR",
    upazilas: [
      "BADARGANJ",
      "GANGACHARA",
      "KAUNIA",
      "RANGPUR SADAR",
      "MITHA PUKUR",
      "PIRGACHHA",
      "PIRGANJ",
      "TARAGANJ",
    ],
  },
  {
    city: "THAKURGAON",
    upazilas: [
      "BALIADANGI",
      "HARIPUR",
      "PIRGANJ",
      "RANISANKAIL",
      "THAKURGAON SADAR",
    ],
  },
  {
    city: "HABIGANJ",
    upazilas: [
      "AJMIRIGANJ",
      "BAHUBAL",
      "BANIACHONG",
      "CHUNARUGHAT",
      "HABIGANJ SADAR",
      "LAKHAI",
      "MADHABPUR",
      "NABIGANJ",
    ],
  },
  {
    city: "MAULVIBAZAR",
    upazilas: [
      "BARLEKHA",
      "JURI",
      "KAMALGANJ",
      "KULAURA",
      "MAULVIBAZAR SADAR",
      "RAJNAGAR",
      "SREEMANGAL",
    ],
  },
  {
    city: "SUNAMGANJ",
    upazilas: [
      "BISHWAMBARPUR",
      "CHHATAK",
      "DAKSHIN SUNAMGANJ",
      "DERAI",
      "DHARAMPASHA",
      "DOWARABAZAR",
      "JAGANNATHPUR",
      "JAMALGANJ",
      "SULLA",
      "SUNAMGANJ SADAR",
      "TAHIRPUR",
    ],
  },
  {
    city: "SYLHET",
    upazilas: [
      "BALAGANJ",
      "BEANI BAZAR",
      "BISHWANATH",
      "COMPANIGANJ",
      "DAKSHIN SURMA",
      "FENCHUGANJ",
      "GOLAPGANJ",
      "GOWAINGHAT",
      "JAINTIAPUR",
      "KANAIGHAT",
      "SYLHET SADAR",
      "ZAKIGANJ",
    ],
  },
];
